print('Hello World, I am Python')
name= input('What is your name? \n > ')
print("Cool name!! "+name+"...let's be friends")
print('I am very smart, look!!')
print("Let's add 2 numbers")
num1= int(input('Give me a number! \n > '))
num2= int(input("Now, give me a second number\n > "))
print("Let's see if it works, well it should work, I am awsome!")
suma=num1+num2
print("the sum of",num1,"+",num2,"is ",suma)
print("Let's do something more dificiult,\nlet's multiply 2 numbers")
num3= int(input('Give me another number! \n > '))
num4= int(input("and now another number\n > "))
print("ok ok ok, 3 times 4, 3 times 4, I am thinking, wait!")
print("I got it 3 times 4 is.....",num3*num4)
print("I told you I could, hehehe")
print("Now something harder, I can tell you if two words are the same or not")
print("Yes, I will tell you False if the are not the same\n and True if the are they the same")
word1=input("First word, tell me\n > ")
word2=input("Second word now\n > ")
respuesta=word1.upper()==word2.upper()
print(respuesta)
print("Want to try again")
print("Two words again")
word1=input("First word\n > ")
word2=input("Second word now\n > ")
respuesta=word1.upper()==word2.upper()
print(respuesta)
print("See!! I am pretty smart")
print("Well,"+name+" was a pleasure talking to you, now I am going away")
print("good bye")
